spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.amqp.rabbit.core.RabbitTemplate: debug
    org.springframework.amqp.rabbit.connection: debug
    com.rabbitmq.client: debug
    org.springframework:
      cache: trace
      amqp.rabbit.core: info
